### ISSUE TITLE
Merge locales bn-BD and bn-IN into a single locale bn

### ISSUE THREAD

**Issue by peiying2** [thunderbird/thunderbird.net-l10n#1]
We are going to merge the two locales into one to fully utilize the community resources. The plan is:

Dev:
- Thunderbird.net-l10n creates an bn folder at repo
- Move bn-BD repo content to bn repo and confirm it's all there (bn-BD has more content in comparison)
- Remove bn-BD, bn-IN repos

Pontoon (l10n);
- Pontoon dev migrates the data to bn (this includes contributors histories)
- L10n PM confirms the update and closes this issue.

**Comment by Sancus** [comment]
Sounds fine. Do you want me to create the bn folder right away?

I will also need to create an empty file in the folder for it to work, so I can just add a 0 byte messages.po

**Comment by peiying2** [comment]
Thanks for your prompt reply. Yes. Let's get this started. I am working on this for several projects. Each one is set up differently. If this is how you add a new locale folder/file, let's treat this request as such case. We will migrate the localized info through Pontoon. Ping me when you are done. Thank you!

**Comment by Sancus** [comment]
Folder added: https://github.com/thundernest/thunderbird.net-l10n/commit/d00bf618c49d5b97b529728508b4ab70a53bb279

Empty file is just a requirement of git to create a folder. It won't add empty folders. Let me know if you need any other help with the migration.

**Comment by peiying2** [comment]
@Sancus thank you for getting this done so quickly. After talking to my peers who are doing the same for other projects, I updated the process in the issue summary area. 

I need you to 
1). move bn-BD repo to bn repo; 
2). remove bn-BD and bn-IN repos. 

After you are done, let me know. I will work with the Pontoon dev to finish the rest. I will comment here once we are completely done on Pontoon side.

**Comment by Sancus** [comment]
No problem. Done in https://github.com/thundernest/thunderbird.net-l10n/commit/ae6a023b91ac0e62e7570142da43195ac3fb364e

I also [updated our website](https://github.com/thundernest/thunderbird-website/commit/955d58b69b50c204177e99696cc8c106f0df4499) to use the new locale and rewrite links to the old locales to /bn/.

**Comment by peiying2** [comment]
You are fast!! I will get back to you once we finish our side of the implementation. Thanks!

**Comment by peiying2** [comment]
Thank you. We are done on our side too.
