### ISSUE TITLE
Stop using fuzzy matches when exporting strings

### ISSUE THREAD

**Issue by flodolo** [thunderbird/thunderbird.net-l10n#10]
Fuzzy matches are most of the time useless, and we have disabled them in all projects recently. Example: https://github.com/mozilla/addons/issues/8753

**Comment by Sancus** [comment]
Thanks for the heads up! This is now disabled in https://github.com/thundernest/thunderbird-website/commit/cdb6a7fefe9cfe47118b1cc0c783440b46575827
