### ISSUE TITLE
Opening quote is missing in a string

### ISSUE THREAD

**Issue by peiying2** [thunderbird/thunderbird.net-l10n#12]
- missing an opening quote: https://pontoon.mozilla.org/ia/thunderbirdnet/LC_MESSAGES/messages.po/?string=279863: `Why does Thunderbird look so old, and why does it take so long to change?" …` 

@jfx2006 rob@thunderbird.net

**Comment by MelissaAutumn** [comment]
Hey @peiying2 apologies for that! I've pushed up a correction, you should see it on Pontoon shortly!
