### ISSUE TITLE
*its* vs *it's*

### ISSUE THREAD

**Issue by peiying2** [thunderbird/thunderbird.net-l10n#3]
Issue: It  should be *it's*, not **its*.
String: [Whether its work or play, you deserve to have privacy when you are online](https://pontoon.mozilla.org/en-CA/thunderbirdnet/LC_MESSAGES/messages.po/?string=231360)... 

Please correct  the string.

**Comment by Sancus** [comment]
https://github.com/thundernest/thunderbird.net-l10n/commit/d53d3351fc4dd4e51bc7d9bee96ba426e7a570c5

Fixed, thanks for the report.
